version: '3.8'
# Environment for local development

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:6.2.7-alpine3.16
    restart: always
    environment:
      REDIS_PASSWORD: 9^ZmT4YWExu8FHPk
    entrypoint: ["/bin/sh", "-c", "redis-server --appendonly yes --requirepass $${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru"]
    ports:
      - "6380:6379"
    volumes:
      - ./db-data/redis/:/data
